// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConnectTunnel(arg1) {
  return window['go']['main']['App']['ConnectTunnel'](arg1);
}

export function DeleteLocalOpenVPNProfile(arg1) {
  return window['go']['main']['App']['DeleteLocalOpenVPNProfile'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function DisconnectTunnel(arg1) {
  return window['go']['main']['App']['DisconnectTunnel'](arg1);
}

export function ForgetOpenVPNPassword(arg1) {
  return window['go']['main']['App']['ForgetOpenVPNPassword'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function ImportOpenVPNProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportOpenVPNProfile'](arg1, arg2, arg3);
}

export function ImportTunnel(arg1, arg2) {
  return window['go']['main']['App']['ImportTunnel'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsDaemonRunning() {
  return window['go']['main']['App']['IsDaemonRunning']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function ManagedActiveServers() {
  return window['go']['main']['App']['ManagedActiveServers']();
}

export function ManagedCheckSetup() {
  return window['go']['main']['App']['ManagedCheckSetup']();
}

export function ManagedCompleteSetup() {
  return window['go']['main']['App']['ManagedCompleteSetup']();
}

export function ManagedConnectOpenVPN(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ManagedConnectOpenVPN'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ManagedConnectServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManagedConnectServer'](arg1, arg2, arg3);
}

export function ManagedConnectServerPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManagedConnectServerPush'](arg1, arg2, arg3);
}

export function ManagedCreatePushAuth(arg1) {
  return window['go']['main']['App']['ManagedCreatePushAuth'](arg1);
}

export function ManagedDefaultDeviceName() {
  return window['go']['main']['App']['ManagedDefaultDeviceName']();
}

export function ManagedDisconnectByTunnelID(arg1) {
  return window['go']['main']['App']['ManagedDisconnectByTunnelID'](arg1);
}

export function ManagedDisconnectOpenVPN(arg1) {
  return window['go']['main']['App']['ManagedDisconnectOpenVPN'](arg1);
}

export function ManagedDisconnectServer(arg1) {
  return window['go']['main']['App']['ManagedDisconnectServer'](arg1);
}

export function ManagedGetSettings() {
  return window['go']['main']['App']['ManagedGetSettings']();
}

export function ManagedGetSetupStep() {
  return window['go']['main']['App']['ManagedGetSetupStep']();
}

export function ManagedListOpenVPNProfiles() {
  return window['go']['main']['App']['ManagedListOpenVPNProfiles']();
}

export function ManagedListOpenVPNSessions() {
  return window['go']['main']['App']['ManagedListOpenVPNSessions']();
}

export function ManagedListServers() {
  return window['go']['main']['App']['ManagedListServers']();
}

export function ManagedLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManagedLogin'](arg1, arg2, arg3);
}

export function ManagedLoginWithPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManagedLoginWithPush'](arg1, arg2, arg3);
}

export function ManagedLogout() {
  return window['go']['main']['App']['ManagedLogout']();
}

export function ManagedPollPushAuth(arg1) {
  return window['go']['main']['App']['ManagedPollPushAuth'](arg1);
}

export function ManagedRegisterDevice(arg1, arg2) {
  return window['go']['main']['App']['ManagedRegisterDevice'](arg1, arg2);
}

export function ManagedSaveServerURL(arg1) {
  return window['go']['main']['App']['ManagedSaveServerURL'](arg1);
}

export function ManagedSetMode(arg1) {
  return window['go']['main']['App']['ManagedSetMode'](arg1);
}

export function SnoozeUpdate(arg1) {
  return window['go']['main']['App']['SnoozeUpdate'](arg1);
}

export function SystemLanguage() {
  return window['go']['main']['App']['SystemLanguage']();
}

export function UninstallApp(arg1) {
  return window['go']['main']['App']['UninstallApp'](arg1);
}

export function UpdateState() {
  return window['go']['main']['App']['UpdateState']();
}
