// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ipc} from '../models';
import {managed} from '../models';

export function CheckForUpdate():Promise<main.UpdateCheckResult>;

export function ConnectTunnel(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function DisconnectTunnel(arg1:string):Promise<void>;

export function GetStats(arg1:string):Promise<ipc.StatsInfo>;

export function ImportTunnel(arg1:string,arg2:string):Promise<ipc.TunnelInfo>;

export function IsDaemonRunning():Promise<boolean>;

export function ListTunnels():Promise<Array<ipc.TunnelInfo>>;

export function ManagedActiveServers():Promise<Array<string>>;

export function ManagedCheckSetup():Promise<boolean>;

export function ManagedCompleteSetup():Promise<void>;

export function ManagedConnectServer(arg1:string,arg2:string,arg3:string):Promise<ipc.TunnelInfo>;

export function ManagedConnectServerPush(arg1:string,arg2:string,arg3:string):Promise<ipc.TunnelInfo>;

export function ManagedCreatePushAuth(arg1:string):Promise<Record<string, any>>;

export function ManagedDefaultDeviceName():Promise<string>;

export function ManagedDisconnectByTunnelID(arg1:string):Promise<void>;

export function ManagedDisconnectServer(arg1:string):Promise<void>;

export function ManagedGetSettings():Promise<main.ManagedSettings>;

export function ManagedGetSetupStep():Promise<string>;

export function ManagedListServers():Promise<Array<managed.ServerInfo>>;

export function ManagedLogin(arg1:string,arg2:string,arg3:string):Promise<main.ManagedLoginResult>;

export function ManagedLoginWithPush(arg1:string,arg2:string,arg3:string):Promise<main.ManagedLoginResult>;

export function ManagedLogout():Promise<void>;

export function ManagedPollPushAuth(arg1:string):Promise<string>;

export function ManagedRegisterDevice(arg1:string,arg2:string):Promise<void>;

export function ManagedSaveServerURL(arg1:string):Promise<void>;

export function ManagedSetMode(arg1:string):Promise<void>;

export function UninstallApp(arg1:boolean):Promise<void>;
